# Generated by Django 4.1 on 2024-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload_image_class",
            name="image_name",
            field=models.TextField(default="No Image"),
            preserve_default=False,
        ),
    ]
