# Generated by Django 4.1 on 2024-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_upload", "0008_upload_image_class_uploaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload_image_class",
            name="predicted_class",
            field=models.CharField(default="", max_length=100),
        ),
    ]
