# Generated by Django 4.1 on 2024-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_upload", "0009_upload_image_class_predicted_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload_image_class",
            name="predicted_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
