# Generated by Django 4.1 on 2024-06-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_upload", "0010_alter_upload_image_class_predicted_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload_image_class",
            name="image_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
