# Generated by Django 4.1 on 2024-06-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_upload", "0011_alter_upload_image_class_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload_image_class",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="upload_image_class",
            name="image_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
